### ISSUE TITLE
Field Shape.coords build polygon Error: Points of LinearRing do not form a closed linestring

### ISSUE THREAD

**Issue by maudslice** [mraad/FileGDB#7]
Hello, I'm trying to use your filegdb implementation to read gdb, by getting the coords of the shape field, I want to calculate these geometries via apache sedona, just like this:
```
    val df = sparkSession.gdb(path, "DLTB_2018")
  .withColumn("coords", concat_ws(",", col("shape.coords")))
  .withColumn("polygon",
    when(col("shape.geomtype") === 1, expr("cast(ST_PointFromText(coords, ',') as STRING)"))
      .when(col("shape.geomtype") === 3, expr("cast(ST_LineStringFromText(coords, ',') as STRING)"))
      .otherwise(expr("cast(ST_PolygonFromText(coords, ',') as STRING)")))
  .withColumn("geom", expr("ST_GeomFromText(polygon)"))
  .drop("shape", "coords", "polygon")
    df.createOrReplaceTempView("t1")
    df.createOrReplaceTempView("t2")

    sparkSession.sql(
      """
        |select ST_Intersection(t1.geom, t2.geom) geom, *
        |from t1, t2
        |where ST_Intersects(t1.geom, t2.geom)
        |""".stripMargin).show(10)
```
 and I'm getting an error when building a polygon using the coords:
```
 Points of LinearRing do not form a closed linestring
	at org.locationtech.jts.geom.LinearRing.validateConstruction(LinearRing.java:91)
	at org.locationtech.jts.geom.LinearRing.<init>(LinearRing.java:86)
	at org.locationtech.jts.geom.GeometryFactory.createLinearRing(GeometryFactory.java:380)
	at org.locationtech.jts.geom.GeometryFactory.createLinearRing(GeometryFactory.java:367)
	at org.locationtech.jts.geom.GeometryFactory.createPolygon(GeometryFactory.java:493)
	at org.apache.sedona.core.formatMapper.FormatUtils.createGeometry(FormatUtils.java:324)
	at org.apache.sedona.core.formatMapper.FormatUtils.readGeometry(FormatUtils.java:291)
	at org.apache.spark.sql.sedona_sql.expressions.ST_PolygonFromText.eval
```
I tried to check shape.coords, some of them are indeed not a closed geometry, I checked it like this:
```
    val df = ss.gdb(path, "SXJXZQH")
      .withColumn("coords", concat_ws(",", col("shape.coords")))
      .select("coords")
    val result = for {
      r <- df.rdd
      coords = r.getAs[String]("coords").split(",").toVector
      v = coords match {
        case Vector(xh, yh, _*) :+ xt :+ yt if (xh, yh) != (xt, yt) => Vector(xh, yh, xt, yt)
        case _ => Vector.empty[String]
      }
    } yield v
    println(result.collect().mkString("\n"))
```
I'm not sure what's wrong, and I'd really like your help. 
jdk: 1.8
spark:3.3.2
sedona: 1.4.0

**Comment by mraad** [comment]
By default the coords in a GDB for a polygon are not closed (last == first) - u have to explicitly close it :-(

**Comment by maudslice** [comment]
Do you mean that if the polygon is not closed, I need to manually add the first coord to the tail of the coords?

**Comment by maudslice** [comment]
This seems to be working, thanks for your reply!
